[package]
name = "joaat-reverser"
version = "0.1.0"
authors = ["Micah Allen"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
rayon = "1.3.0"
pad = "0.1.6"
base_custom = "0.2.0"