[package]
name = "joaat-reverser"
version = "0.1.0"
authors = ["Micah Allen"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
crossbeam = "0.7.2"
rayon = "1.2.0"
base_custom = "0.2.0"